language: cpp
compiler: gcc
dist: precise
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -q
- sudo apt-get install -y gcc-6
- sudo apt-get install -y g++-6

before_script:
- export CC=gcc-6
- export CXX=g++-6
- wget https://cmake.org/files/v3.8/cmake-3.8.1-Linux-x86_64.tar.gz -O CMake.tar.gz --no-check-certificate && tar -xvf CMake.tar.gz && export CMake=$PWD/cmake-3.8.1-Linux-x86_64/bin/cmake

script:
- export UEADB="./UEADB"
- mkdir build-debug && cd build-debug && ${CMake} .. -DCMAKE_BUILD_TYPE=Debug && make && make test && echo "Debug testing log:" && cat "Testing/Temporary/LastTest.log" && cd bin && sh ./scripts/TestUEADB.sh && cd .. && cd ..
- mkdir build-release && cd build-release && ${CMake} .. -DCMAKE_BUILD_TYPE=Release && make && make test && echo "Release testing log:" && cat "Testing/Temporary/LastTest.log" && cd bin && sh ./scripts/TestUEADB.sh && cd .. && cd ..
